# Change these first
owner: alexnuttinck # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Alexandre Nuttinck website
    url: https://alexnuttinck.dev
  - name: Le Pressoir
    url: https://www.lepressoir.be/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.alexnuttinck.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Alexnuttinck Status
  introTitle: "alexnuttinck **status page**"
  introMessage: This **status page** provides **real-time** data about the services I want to monitor. It is based on the open-source [Upptime](https://github.com/upptime/upptime) tool.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
